#!/usr/bin/env bash

#MISE description="Build the CLI"

cid=$(devcontainer up --workspace-folder $(pwd)/zmk | jq -r .containerId)
docker exec -w /workspaces/zmk -it $cid west init -l app/
docker exec -w /workspaces/zmk -it $cid west update

docker exec -w /workspaces/zmk/app -it $cid west build -p -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="/workspaces/zmk-config/config" -DZMK_EXTRA_MODULES="/workspaces/zmk-config/modules/tri-state"
cp zmk/app/build/zephyr/zmk.uf2 corne_left.uf2

docker exec -w /workspaces/zmk/app -it $cid west build -p -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG="/workspaces/zmk-config/config" -DZMK_EXTRA_MODULES="/workspaces/zmk-config/modules/tri-state"
cp zmk/app/build/zephyr/zmk.uf2 corne_right.uf2
